version: '3.7'
name: 'warehouse-management'
services: 
  warehouse-service:
    image: ghcr.io/epicsamuray/warehousemgr:0.1.0
    container_name: warehouse-service
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://root:example@mongo:27017/
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/